CREATE TABLE `usershares` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(30) NULL,
    `last_name` VARCHAR(30) NULL,
    `user_name` VARCHAR(30) NULL,
    `club` VARCHAR(64) NULL,
    `country` VARCHAR(150) NULL,
    `state_province` VARCHAR(150) NULL,
    `local_govt` VARCHAR(150) NULL,
    `town_city` VARCHAR(150) NULL,
    `password` VARCHAR(96) NOT NULL,
    `email` VARCHAR(150) NULL,
    `phone_number` VARCHAR(30) NULL,
    `activation_status` TINYINT(1) NOT NULL DEFAULT 0,
    `activation_key` VARCHAR(64) NOT NULL,
    `recovery_data` VARCHAR(1024) NULL,
    `session_id` VARCHAR(128) NULL,
    `activity_status` VARCHAR(30) NULL,
    `suspended_until` DATETIME NULL,
    `shadow_banned_until` DATETIME NULL,
    `last_seen` DATETIME NULL,
    `registered_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified_at` DATETIME on update CURRENT_TIMESTAMP NULL,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB